version: '3.7'

x-base: &base
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"
services:
  ha-terminator-api:
    # this instance could be change to ssl terminator + ha 
    image: haproxy:lts
    restart: unless-stopped
    ports:
      - "8443:8443"
      # stats
      - "7999:7999"
    volumes:
      # haproxy
      - type: bind
        source: ./conf
        target: /usr/local/etc/haproxy
        read_only: true
      - type: bind
        source: ./certs
        target: /etc/web_cert
        read_only: true


